name: CI - Test and Build Image

on:
  push:
    branches:
      - master
      - 'feature/**'
  pull_request:
    branches:
      - master

jobs:
  test:
    name: 🧪 Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q

  build:
    name: 🐳 Build & Push Docker Image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # set up Docker buildx & QEMU for multi-platform (optional)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # LOGIN to your registry: choose one

      # — GitHub Container Registry (no extra secrets needed) —
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # — Docker Hub (requires DOCKERHUB_USERNAME & DOCKERHUB_TOKEN) —
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          # set to true if you want to push to your registry
          push: true
          # example tags for GHCR:
          tags: |
            ghcr.io/${{ github.repository_owner }}/fastapi-app:latest
            ghcr.io/${{ github.repository_owner }}/fastapi-app:${{ github.sha }}
          # or for Docker Hub:
          # tags: |
          #   ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:latest
          #   ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:${{ github.sha }}
